### PR TITLE
move pip cache above

### PR DESCRIPTION
**Pull request by carlosggarcia**
I think the cache of pip is doing nothing because it's done after pip installation. Trying to move it before

### CODE REVIEW

**Comment by carlosggarcia** [comment]
Now it's using cache but the slowest part is running the installation of NaMaster, CCL and CAMB. Isn't it possible to cache those too? (the downloaded files are cached, but not the installation)

**Comment by damonge** [comment]
FYI namaster does not have wheels

**Comment by carlosggarcia** [comment]
Are you sure? I think pip creates it. See line 114 of this action https://github.com/xC-ell/xCell/runs/2827608349?check_suite_focus=true#step:6:114

**Comment by damonge** [comment]
sorry, I meant they're not on pypi, so they need to be built every time you install it.

**Comment by carlosggarcia** [comment]
But the idea with having the cache is avoiding reinstalling again unless the version changes, right?

**Comment by damonge** [comment]
sure, sure, just letting you know in case it plays a role

**Comment by carlosggarcia** [comment]
Got it! Based on https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d

**Comment by carlosggarcia** [comment]
Closing this PR and opening a new one after squashing commits

**Comment by carlosggarcia** [comment]
Reopen because I saw that there's only 1 commit that will be merged

**Review by damonge — APPROVED** [review]
LGTM

**Pull request merged**
